name: CI test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: "*/* * 20 * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # workflow steps
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: docker-compose
        run: docker-compose up -d

      - name: Install sql-migrate
        run: go install github.com/rubenv/sql-migrate/...@latest

      - name: Run migrations
        run: sql-migrate up -config=sql_migrate.yml

      - name: Test
        run: go test -v -cover ./...
